### ISSUE TITLE
A Bit Unclear On How To Use

### ISSUE THREAD

**Issue by bonedaddy** [danderson/natlab#3]
I'm reading through the readme, and the source code itself, but I'm a little unsure of how exactly one can use this testbed. I'm experimenting with different NAT traversal solutions, and came across this repository while looking for methods of testing NAT traversal solutions.

The README is pretty clear on *what* this library does and the tests it performs, but its extremely unclear on how you  can either run the pre-built in tests, or how you can develop tests that use this testbed.

For example, I assume I need to deploy the docker-compose file, but then what? Do I also need to create another image within that compose file that loads the NAT Traversal software I want to test? etc...

**Comment by danderson** [comment]
This codebase is vastly incomplete and not currently usable. Sorry. I'm not actively working on it right now, but may do so in the coming months to bring it up to a usable state.

**Comment by bonedaddy** [comment]
Ah okay makes sense, thanks.
